#include <stdlib.h>
#include <iostream>
#include <vector>
#include <string>

std::string sGear[103] =
{
	"Abacus",
	"Acid",
	"Alchemist's Fire",
	"Arrows (20)",
	"Blowgun Needles (20)",
	"Crossbow Bolts (20)",
	"Sling bullets (20)",
	"Antitoxin",
	"Arcane Focus (Crystal)",
	"Arcane Focus (Orb)",
	"Arcane Focus (Rod)",
	"Arcane Focus (Staff)",
	"Arcane Focus (Wand)",
	"Backpack",
	"Ball Bearings (1000)",
	"Barrel",
	"Basket",
	"Bedroll",
	"Bell",
	"Blanket",
	"Block and tackle",
	"Book",
	"Bottle",
	"Bucket",
	"Caltrops",
	"Candle",
	"Case, Crossbow Bolt",
	"Case, Map or Scroll",
	"Chain, 10 ft",
	"Chalk",
	"Chest",
	"Clothes, common",
	"Clothes, costume",
	"Clothes, fine",
	"Clothes, traveler's",
	"Component pouch",
	"Crowbar",
	"Druidic Focus (Sprig of mistletoe)",
	"Druidic Focus (Totem)",
	"Druidic Focus (Wooden staff)",
	"Druidic Focus (Yew wand)",
	"Fishing tackle",
	"Flask",
	"Grappling hook",
	"Hammer",
	"Hammer, sledge",
	"Healer's Kit",
	"Holy Symbol (Amulet)",
	"Holy Symbol (Emblem)",
	"Holy Symbol (Reliquary)",
	"Holy Water",
	"Hourglass",
	"Hunting trap",
	"Ink",
	"Ink pen",
	"Jug",
	"Kit, climber's",
	"Kit, disguise",
	"Kit, forgery",
	"Kit, herbalism",
	"Kit, healer's",
	"Kit, mess",
	"Kit, poisoner's",
	"Ladder (10 ft)",
	"Lamp",
	"Lantern, bullseye",
	"Lantern, hooded",
	"Lock",
	"Magnifying glass",
	"Manacles",
	"Mirror, steel",
	"Oil (flask)",
	"Paper (one sheet)",
	"Parchment (one sheet)",
	"Perfume (vial)",
	"Pick, miner's",
	"Piton",
	"Poison, basic (vial)",
	"Pole (10 ft)",
	"Pot, iron",
	"Potion of healing",
	"Pouch",
	"Quiver",
	"Ram, portable",
	"Robes",
	"Rope, hempen (50 ft)",
	"Rope, silk (50 ft)",
	"Sack",
	"Scale, merchant's",
	"Sealing wax",
	"Shovel",
	"Signal whistle",
	"Signet ring",
	"Soap",
	"Spellbook",
	"Spikes, iron (10)",
	"Spyglass",
	"Tent, two person",
	"Tinderbox",
	"Torch",
	"Vial",
	"Waterskin",
	"Whetstone"

};

int randGear{};


void rollGear()
{
	int randGear = rand() % 103;

	std::cout << "GEAR: " << sGear[randGear] << '\n';
	
};